### ISSUE TITLE
Dependencies need cleanup

### ISSUE THREAD

**Issue by mattray** [jjasghar/knife-maas#9]
In the knife-maas.gemspec "oauth" is un-versioned, which could be an issue. "chef' is "~> 12.0.0" which won't pick up 12.1 when it lands.

**Comment by jjasghar** [comment]
Slating this for 1.0.1

**Comment by jjasghar** [comment]
b5267e4 should resolve this.

**Comment by jjasghar** [comment]
https://github.com/jjasghar/knife-maas/pull/12
